### PR TITLE
Adding Examples to the Readme.md

### PR DESCRIPTION
**Pull request by cdesch**
Adding Examples for those of us who struggle with basics

### CODE REVIEW

**Comment by drewolson** [comment]
I already have several examples in the readme. I'd prefer not to add phoenix-specific examples. Thanks!

**Comment by cdesch** [comment]
That is fine. Do you think there is somewhere else we could share them?

**Comment by drewolson** [comment]
If you'd like to create a phoenix-specific example, I'd be happy to link to it from the README (assuming I consider it to be idiomatic).

**Comment by cdesch** [comment]
Another Markdownfile in the project, or in a wiki, or just linked to a different site? I can do either, which do you prefer?

**Comment by drewolson** [comment]
Let's try the wiki, I like that idea.

**Pull request closed without merging**
